//! Generate a binary-lane recipe from a surveyed local artifact.
//!
//! The survey itself is produced by `elda-build` (it needs archive decoders);
//! this module only turns that plain description into `pkg.lua`. Keeping the
//! two apart is what lets the recipe layer stay free of archive dependencies.

use std::fs;
use std::path::Path;

use elda_types::{ArtifactAcquisition, ArtifactEntryKind, ArtifactSurvey};

use super::model::{ImportOptions, ImportReport};
use crate::error::RecipeError;

/// Write `pkg.lua` for a surveyed artifact and describe what was written.
pub fn write_local_artifact_recipe(
    recipes_dir: &Path,
    survey: &ArtifactSurvey,
    acquisition: &ArtifactAcquisition,
    options: &ImportOptions,
) -> Result<ImportReport, RecipeError> {
    let name = survey.name.clone().ok_or_else(|| {
        RecipeError::InvalidInput(format!(
            "could not infer a package name from `{}`; rename the file to `<name>-<version>...` or add the recipe manually",
            survey.file_name
        ))
    })?;
    validate_package_name(&name)?;

    let recipe_dir = recipes_dir.join(&name);
    let pkg_lua = recipe_dir.join("pkg.lua");
    if pkg_lua.exists() && !options.replace {
        return Err(RecipeError::InvalidInput(format!(
            "metadata for `{name}` already exists; pass `--replace` to overwrite it"
        )));
    }
    fs::create_dir_all(&recipe_dir)?;
    fs::write(&pkg_lua, render_pkg_lua(&name, survey, acquisition))?;

    Ok(ImportReport {
        recipe_name: name,
        recipe_dir,
        source_options: Vec::new(),
        selected_source_option: None,
        imported_pkg_lua: false,
        imported_build_lua: false,
        imported_patches: false,
        generated_pkg_lua: true,
        reused_existing_pkg_lua: false,
        generated_build_lua: false,
        imported_legacy_pkgdeps: false,
        imported_legacy_bldit: false,
        wrote_legacy_summary: false,
    })
}

fn validate_package_name(name: &str) -> Result<(), RecipeError> {
    let acceptable = !name.is_empty()
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | '+' | '.'));
    if acceptable {
        return Ok(());
    }
    Err(RecipeError::InvalidInput(format!(
        "inferred package name `{name}` is not a usable Elda package name"
    )))
}

fn render_pkg_lua(
    name: &str,
    survey: &ArtifactSurvey,
    acquisition: &ArtifactAcquisition,
) -> String {
    let version = survey.version.as_deref().unwrap_or("0.1.0");
    let upstream = acquisition.url().unwrap_or_default();

    let mut source = String::from("  source = {\n");
    source.push_str(&format!(
        "    kind = \"{}\",\n",
        survey.format.source_kind()
    ));
    match acquisition {
        ArtifactAcquisition::Url(url) => {
            source.push_str(&format!("    url = \"{}\",\n", escape(url)));
        }
        ArtifactAcquisition::LocalOnly => {
            source.push_str(&format!(
                "    url = \"file://{}\",\n",
                escape(&survey.file_name)
            ));
        }
    }
    source.push_str(&format!("    sha256 = \"{}\",\n", escape(&survey.sha256)));
    if survey.strip_components > 0 {
        source.push_str(&format!(
            "    strip_components = {},\n",
            survey.strip_components
        ));
    }
    if let Some(binary) = survey.sole_executable() {
        source.push_str(&format!(
            "    binary = \"{}\",\n",
            escape(strip_leading(&binary.path, survey.strip_components))
        ));
    }
    source.push_str("  },\n");

    let provenance = match acquisition {
        ArtifactAcquisition::Url(_) => String::new(),
        ArtifactAcquisition::LocalOnly => format!(
            "-- No upstream URL recorded for `{}`; this package cannot be re-fetched or upgraded.\n",
            escape(&survey.file_name)
        ),
    };

    let mut out = String::new();
    out.push_str("-- Generated by `elda a` from a local artifact.\n");
    out.push_str(&format!("-- artifact: {}\n", escape(&survey.file_name)));
    out.push_str(&format!("-- format:   {}\n", survey.format.label()));
    out.push_str(&provenance);
    out.push_str("\npkg = {\n");
    out.push_str(&format!("  name = \"{}\",\n", escape(name)));
    out.push_str("  description = \"\",\n");
    out.push_str("  licenses = {},\n");
    out.push_str(&format!("  upstream = \"{}\",\n", escape(upstream)));
    out.push_str("  epoch = 0,\n");
    out.push_str(&format!("  version = \"{}\",\n", escape(version)));
    out.push_str("  rel = 1,\n");
    out.push_str("  arch = { \"amd64\" },\n");
    out.push_str("  kind = \"normal\",\n\n");
    out.push_str(&source);
    for empty in [
        "depends",
        "makedepends",
        "checkdepends",
        "recommends",
        "suggests",
        "supplements",
        "enhances",
        "provides",
        "conflicts",
        "replaces",
        "conffiles",
        "sysusers",
        "tmpfiles",
        "alternatives",
        "hooks",
        "provider_assets",
        "flags_default",
        "flags_allowed",
        "flags_implies",
        "flags_conflicts",
        "subpackages",
    ] {
        out.push_str(&format!("  {empty} = {{}},\n"));
    }
    out.push_str("}\n");
    out
}

/// Drop the archive root that staging will strip, so recorded paths match
/// what actually lands in the prefix.
fn strip_leading(path: &str, strip_components: u32) -> &str {
    let mut remainder = path;
    for _ in 0..strip_components {
        match remainder.split_once('/') {
            Some((_, rest)) => remainder = rest,
            None => break,
        }
    }
    remainder
}

fn escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Human-readable one-line summary of what a survey found.
#[must_use]
pub fn survey_summary(survey: &ArtifactSurvey) -> String {
    let executables = survey.executables().len();
    let dropped = survey.dropped().len();
    let mut parts = vec![format!("{} member(s)", survey.entries.len())];
    if executables > 0 {
        parts.push(format!("{executables} executable"));
    }
    for (kind, label) in [
        (ArtifactEntryKind::ManPage, "man"),
        (ArtifactEntryKind::Completion, "completion"),
        (ArtifactEntryKind::License, "license"),
    ] {
        let count = survey.by_kind(kind).len();
        if count > 0 {
            parts.push(format!("{count} {label}"));
        }
    }
    if dropped > 0 {
        parts.push(format!("{dropped} dropped"));
    }
    parts.join(", ")
}

#[cfg(test)]
mod tests;
