use super::root::Command;

pub(super) fn command_name(command: &Command) -> String {
    match command {
        Command::A(_) => "a",
        Command::Add(_) => "add",
        Command::I(_) => "i",
        Command::Ig(_) => "ig",
        Command::Ib(_) => "ib",
        Command::Rm(_) => "rm",
        Command::U(_) => "u",
        Command::Sync(_) => "sync",
        Command::Ls(_) => "ls",
        Command::Search(_) => "search",
        Command::Info(_) => "info",
        Command::Files(_) => "files",
        Command::Verify(_) => "verify",
        Command::Reverify(_) => "reverify",
        Command::Why(_) => "why",
        Command::Rdeps(_) => "rdeps",
        Command::Versions(_) => "versions",
        Command::Pin(_) => "pin",
        Command::Unpin(_) => "unpin",
        Command::Hold(_) => "hold",
        Command::Unhold(_) => "unhold",
        Command::Adopt(_) => "adopt",
        Command::Downgrade(_) => "downgrade",
        Command::Diff(_) => "diff",
        Command::Check => "check",
        Command::Doctor => "doctor",
        Command::Version => "version",
        Command::Init => "init",
        Command::Recover => "recover",
        Command::Rollback(_) => "rollback",
        Command::FixTriggers => "fix-triggers",
        Command::Autoremove => "autoremove",
        Command::Rmt { .. } => "rmt",
        Command::Rc { .. } => "rc",
        Command::Ci { .. } => "ci",
        Command::Vendor { .. } => "vendor",
        Command::Forge { .. } => "forge",
        Command::Host { .. } => "host",
        Command::Publish { .. } => "publish",
        Command::Git { .. } => "git",
        Command::AppImage { .. } => "appimage",
        Command::Pf { .. } => "pf",
        Command::Fl { .. } => "fl",
        Command::Mg { .. } => "mg",
        Command::Review { .. } => "review",
        Command::State { .. } => "state",
        Command::Cache { .. } => "cache",
        Command::Daemon { .. } => "daemon",
        Command::Ext { .. } => "ext",
        Command::Qa { .. } => "qa",
        Command::Trigger { .. } => "trigger",
        Command::Maint { .. } => "maint",
        Command::Config { .. } => "config",
    }
    .to_owned()
}
